name: Ruby

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run all specs
      run: |
        bundle exec rspec --format=documentation

    - name: Run Rubocop
      run: |
        bundle exec rubocop


